### ISSUE TITLE
Missing generatePrivateKey function

### ISSUE THREAD

**Issue by ArthurHoeke** [Zilliqa/Zilliqa-JavaScript-Library#262]
**Describe the bug**
The crypto class is supposed to have a function to generate a private key and says so in the documentation, though when trying to use that function and looking through the code it doesn't exist. How do I generate a private key?

**To Reproduce**
1. Go to https://github.com/Zilliqa/Zilliqa-JavaScript-Library/tree/dev/packages/zilliqa-js-crypto
2. See generatePrivateKey() which would return a private key
3. https://github.com/Zilliqa/Zilliqa-JavaScript-Library/blob/dev/packages/zilliqa-js-crypto/src/util.ts misses the function

**Expected behavior**
Function exists in utils

**Comment by mickys** [comment]
https://github.com/Zilliqa/Zilliqa-JavaScript-Library/blob/dev/packages/zilliqa-js-crypto/src/index.ts
```
import * as schnorr from './schnorr';
export * from './signature';
```
this should export the generatePrivateKey() method to the @zilliqa-js/crypto package upon instantiation.

Thou for actual usage i suggest you implement an HD Wallet generator for your private keys based on some seed words.
Check out https://github.com/cryptolandtech/moonlet-core/blob/master/src/core/utils/hdkey.ts

For the bug report itself, the reproduction steps should really include a "failing example" with the way you instantiate the object where it does not actually export the method :) instead of code inspection.
