### ISSUE TITLE
FetchError: invalid json response body

### ISSUE THREAD

**Issue by fabianriewe** [Zilliqa/Zilliqa-JavaScript-Library#301]
**Describe the bug**
When making API calls to `https://api.zilliqa.com/` trough `zilliqa.blockchain.getTxBlock(BlockNum)` requests sometimes fail and are not handled correctly, resulting in the following error:

```
FetchError: invalid json response body at https://api.zilliqa.com/ reason: Unexpected token < in JSON at position 0
    at /Users/fabianriewe/WebstormProjects/kyve/integrations/node_modules/cross-fetch/node_modules/node-fetch/lib/index.js:254:32
    at processTicksAndRejections (node:internal/process/task_queues:94:5) {
  type: 'invalid-json'
}
```

Unfortunately, I am not able to log the actual response from the server. 

The full implementation can be found here:
https://github.com/KYVENetwork/kyve/blob/master/integrations/zilliqa/src/index.ts#L44

Is there any way to handle this error or maybe raise the API response?

**Comment by bb111189** [comment]
This is likely to be the case where the public API endpoint responded with a `502 bad gateway` error intermittently. This issue will be resolved in the core protocol in the next release v8.1.0. 

In the interim, you can handle the exception and re-try it

**Comment by realsteel85** [comment]
The websocket connects to api.zilliqa.com but you don't know on which node you are querying this.

When you then start processing the data from the websocket with zilliqa-js, it may happen that zilliqa-js cannot find the data because the data is not yet available on another node. The nodes are never 100% in sync.

When I run both the websocket and the zilliqa-js on 1 node (in this case the seed node of zillacracy) I no longer get this message.

**Comment by noel-yoo** [comment]
https://github.com/Zilliqa/Zilliqa/releases/tag/v8.1.1
> This hot-fix addresses 502 error network issue observed intermittently on staking raw endpoint by some SSN operators. (#2707)
